# Created with YamlCreate.ps1 v2.0.0 $debug=AUSU.5-1-19041-1237
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Adobe.Acrobat.Reader.64-bit
PackageVersion: 21.007.20099
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /sAll /rs /rps /l /re
  SilentWithProgress: /sAll /rs /rps /l /re
UpgradeBehavior: install
FileExtensions:
- pdf
- pdfa
- pdfx
- xfx
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerUrl: https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100720099/AcroRdrDCx642100720099_en_US.exe
  InstallerSha256: 5C96988674B82E22DEC0F2C7DDED08D2E299328BD26F55B241529B879FA819E4
- InstallerLocale: de-DE
  Architecture: x64
  InstallerUrl: https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100720099/AcroRdrDCx642100720099_de_DE.exe
  InstallerSha256: AF765763EB4DE3019B62C11F6E2C740C6BF404F4CA70B566FB1079B2BF943FCC
- InstallerLocale: es-ES
  Architecture: x64
  InstallerUrl: https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100720099/AcroRdrDCx642100720099_es_ES.exe
  InstallerSha256: 37D25655E7F481E6A38AE93FCC74C24AEDE48A2EAD93CFE9DBD3AA70F972F58A
- InstallerLocale: fr-FR
  Architecture: x64
  InstallerUrl: https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100720099/AcroRdrDCx642100720099_fr_FR.exe
  InstallerSha256: 287A1CD200225D8B9718EA2B2DCB10ADE859832C2BA90BB00800FF4A0ACEE5FC
- InstallerLocale: ja-JP
  Architecture: x64
  InstallerUrl: https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100720099/AcroRdrDCx642100720099_ja_JP.exe
  InstallerSha256: A123BD43AAF3FCF6FAE34C5D1CE77E01DC40EC621C82D9E63BCF9625A639812C
- InstallerLocale: nl-NL
  Architecture: x64
  InstallerUrl: https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100720099/AcroRdrDCx642100720099_nl_NL.exe
  InstallerSha256: A94DA8B22A03246FD2E7A2CC5A37A0A70B8786AA09AD77DBB1CAAEE0A6AA001E  
ManifestType: installer
ManifestVersion: 1.0.0
